---
- name: changing hostname
  hostname: name="{{ inventory_hostname }}"
  register: "hostname_status"
  become: true
  when: ansible_fqdn != ansible_host


- name: change /etc/hosts to remove old hostname
  tags:
    - hosts
  become: true
  lineinfile: state=present
    dest=/etc/hosts
    line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_host }}"
    regexp="^{{ ansible_default_ipv4.address }}"
  when: ansible_fqdn != inventory_hostname

- name: print hostnames
  debug: 
    msg: "ansible_fqdn is {{ ansible_fqdn }}, inventory_hostname is {{ inventory_hostname }}"

